// <auto-generated />
namespace FPCS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _13_10_2016_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13_10_2016_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201610131114474_13_10_2016_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
